= HTML to JSON transformation policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-html-json/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-html-json/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Scope

|===
|onRequest|onResponse|onRequestContent|onResponseContent
||||X
|===

== Description

You use the `html-json` transformation policy to transform the response content.

This policy is based on the https://jsoup.org[jsoup^] HTML parser.
In APIM, all you need to do is provide your JSON field names with the
associated selectors.

=== Policy identifier

You can enable or disable the policy with policy identifier `html-json`.

== Configuration

You can configure the policy with the following options:

|===
|Property |Required |Description |Type
|jsonName |true|Name of the JSON field to contain the result of the selection|String
|selector |true|HTML/CSS selector used to select an element and get the text|String
|array    |false|Used to determine whether the selection needs to be returned as an array|Boolean
|===

== Examples

[source, json]
----
"html-json": {
    "selectors":
        [
            {
                "array": false,
                "jsonName": "test",
                "selector": ".class h1"
            },
            {
                "array": true,
                "jsonName": "testArray",
                "selector": ".container ul"
            }
        ]
    }
}
----
